# Site settings
title: Kuona - Build Analytics
email: graham@grahambrooks.com
description: > # this means to ignore newlines until "baseurl:"
  Continous Delivery and Continuous Integration systems need
  dashboards that not only show the current state of projects but also
  track trends and show how well your system is performing. Kuona
  intends to provide that capability.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kuona.github.io" # the base hostname & protocol for your site
twitter_username: grahamcbrooks
github_username:  grahambrooks

# Build settings
markdown: kramdown
highlighter: pygments

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

